name: CI - Devops Kata (Docker/Python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set image version
        run: |
          docker build \
            -t difervi/devops-kata:${{ env.IMAGE_TAG }} \
            -t difervi/devops-kata:latest \
            .
      - name: Running test inside Docker container
        run: |
          docker run --rm difervi/devops-kata:${{ env.IMAGE_TAG }}

      - name: Push Docker images
        run: |
          docker push difervi/devops-kata:${{ env.IMAGE_TAG }}
          docker push difervi/devops-kata:latest